### PR TITLE
Refactored the code

### PR DESCRIPTION
**Pull request by ChiragAgg5k**
- used prettier to format css
- added gitignore template for django
- removed cache files
- removed unused imports
- added requirements.txt file

### CODE REVIEW

**Comment by ChiragAgg5k** [comment]
Closes issue #17

**Review by Dv04 — APPROVED** [review]
This is good. Approved for Merge. But the request won't be closed as there are some other tasks that can still be implemented. Would you be working on it further @ChiragAgg5k?

**Comment by ChiragAgg5k** [comment]
Yeah i can work it on further @Dv04

**Comment by ChiragAgg5k** [comment]
could you add the hacktoberfest label to it? idk if it counts now though

**Comment by Dv04** [comment]
@ChiragAgg5k Great than I will keep you as assigned.

**Pull request merged**
